### ISSUE TITLE
ActiveSupport 4.2 breaks functionality

### ISSUE THREAD

**Issue by leprasmurf** [technicalpickles/pager_duty-connection#12]
With ActiveSupport 4.2 installed, the following error is returned:

1.9.3-p551 :001 > require pager_duty-connection
NameError: undefined local variable or method `pager_duty' for main:Object
        from (irb):1
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'
1.9.3-p551 :002 > require 'pager_duty-connection'
NameError: uninitialized constant ActiveSupport::Autoload
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/number_helper.rb:3:in `<module:NumberHelper>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/number_helper.rb:2:in `<module:ActiveSupport>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/number_helper.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric/conversions.rb:2:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/core_ext/numeric.rb:3:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:2:in `block in <top (required)>'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `each'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/activesupport-4.2.0/lib/active_support/core_ext.rb:1:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/pager_duty-connection-0.1.0/lib/pager_duty/connection.rb:3:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:54:in `require'
        from /usr/local/rvm/gems/ruby-1.9.3-p551@pagerduty2/gems/pager_duty-connection-0.1.0/lib/pager_duty-connection.rb:2:in `<top (required)>'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/site_ruby/1.9.1/rubygems/core_ext/kernel_require.rb:39:in `require'
        from (irb):2
        from /usr/local/rvm/rubies/ruby-1.9.3-p551/bin/irb:12:in `<main>'1.9.3-p551 

I was able to specify ActiveSupport version 4.0.1 and the require now works as expected.

**Comment by ruphin** [comment]
Another workaround is to ```require 'active_support'``` before ```require 'pager_duty-connection```

**Comment by keiththomps** [comment]
This was resolved by #13
