### ISSUE TITLE
Rails 5 support?

### ISSUE THREAD

**Issue by nubecoder** [technicalpickles/pager_duty-connection#23]
There is currently a dependency for activesupport (< 5.0, >= 3.2).
Has this not been tested on Rails 5 or is there some issue with activesupport > 5.0?

**Comment by keiththomps** [comment]
None of the apps that I'm currently using this in are on Rails 5, but it shouldn't be too hard to determine if this is necessary.

**Comment by technicalpickles** [comment]
https://github.com/technicalpickles/pager_duty-connection/pull/26 fixed this, and it's now released in 1.1.0
